# Generated by Django 4.2.1 on 2023-05-25 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animation',
            name='link',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='link',
        ),
        migrations.AddField(
            model_name='animation',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='animation'),
        ),
        migrations.AddField(
            model_name='drawing',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='drawing'),
        ),
    ]
