# Generated by Django 4.2.1 on 2023-05-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0002_remove_animation_link_remove_drawing_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='file',
            field=models.FileField(upload_to='animation'),
        ),
        migrations.AlterField(
            model_name='drawing',
            name='file',
            field=models.FileField(upload_to='drawing'),
        ),
    ]
