# Generated by Django 4.2.1 on 2023-05-25 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0003_alter_animation_file_alter_drawing_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drawing',
            name='status',
            field=models.CharField(choices=[('pending', '승인필요'), ('approved', '승인됨'), ('active', '활성'), ('inactive', '비활성')], default='active', max_length=15),
        ),
    ]
