# Generated by Django 4.2.1 on 2023-05-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0005_alter_animation_drawing_alter_drawing_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='drawing',
            options={'ordering': ['-created_at']},
        ),
    ]
