# Generated by Django 4.2.1 on 2023-05-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drawing', '0006_alter_animation_options_alter_drawing_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animation',
            name='purpose',
            field=models.CharField(choices=[('wait1', '대기1'), ('wait2', '대기2'), ('listen1', '듣는중1'), ('listen2', '듣는중2'), ('talking1', '말하는중1'), ('talking2', '말하는중2')], max_length=10),
        ),
    ]
