# Generated by Django 4.2.1 on 2023-05-25 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_alter_message_room_alter_room_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='audio_url',
            field=models.URLField(),
        ),
    ]
