# Generated by Django 4.2.1 on 2023-05-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0004_alter_message_audio_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
