# Generated by Django 4.2.1 on 2023-05-25 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0005_room_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-created_at']},
        ),
    ]
